export {default as RootPage} from './Root'
export {default as HomePage} from './HomePage/HomePage'
export {default as UserPage} from './UsersPage/UsersPage'
export {default as UserDetailPage} from './UserDetailPage/UserDetail'
export {default as ErrorPage} from './error-page'
export {default as PostDetailPage} from './PostDetail/PostDetails'